<a href="https://colab.research.google.com/github/Abayrakdar/Testing/blob/main/Week4_Python_Session_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import numpy as np
# How to create Arrays using Numpy, Arrays look like Matrix
arr=np.array([1,2,3])
print(arr)
# To check the dimension of our array:
arr_0=np.array([12])
print(arr_0) # This a 1 dimensional array is it has 1 row
arr_0.ndim # This is to check the dimension of an array, it looks for the number of the rows.
arr_0.ndim # .ndim in this example is giving 1 because it contains Only 1 set of bracket.
# print(arr_0)
arr.shape # This gives the shape as (3,) that is 3 column

[1 2 3]
[12]


(3,)

In [22]:
# 1 dimension
arr1=np.array([1,2,3,4])
print(arr1)
arr1.shape # This tells us the shape is 4 that is 4 columns

[1 2 3 4]


(4,)

In [23]:
arr2=np.array([[1,2,3,4],[4,5,6,7]])
print(arr2)
arr2.shape # Here shape is saying that we have 2 columns and 4 elements in each

[[1 2 3 4]
 [4 5 6 7]]


(2, 4)

In [24]:
arr3=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(arr3)
arr3.ndim # .ndim gives you the number of brackets only, so if you add none-needed brackets .ndim will increase
# This is why arr3.ndim is giving 2 in this example.
arr3.shape # shape is saying that we have 4 columns and 4 elements in each.
# Shape tells you what elements you have the number of columns and number of rows.

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


(4, 4)

In [25]:
arr4=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]])
print(arr4)
arr4.ndim
arr4.shape # shape is saying that we have 5 columns and 4 rows (Rows are sublists)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


(5, 4)

In [30]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [33]:
np.random.rand(4)

array([0.90182342, 0.45548607, 0.91752702, 0.88346487])

In [35]:
np.arange(10,25,20)

array([10])

In [36]:
arr6=np.array([[[1,2,3,4],[4,5,6,7]],[[8,9,10,11],[12,13,14,15]]])
print(arr6)
arr6.shape # Note here what shape has given 2 major columns in each 2 other columns in each first columns and 2 rows in each columns.

[[[ 1  2  3  4]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


(2, 2, 4)

In [41]:
# Transposing a Matrix
data_2=np.array([[0,1,2],[3,4,5]])
print(data_2)
data_2.shape

[[0 1 2]
 [3 4 5]]


(2, 3)

In [44]:
np.transpose(data_2) # it gives me 2 rows and 3 columns when transposing

array([[0, 3],
       [1, 4],
       [2, 5]])

In [49]:
data=np.array(
    [[
        [12,67],
      [35,90]
      ],
      [
          [12,3],
       [8,27]
      ]])
data


array([[[12, 67],
        [35, 90]],

       [[12,  3],
        [ 8, 27]]])

In [50]:
data.shape

(2, 2, 2)

In [52]:
data.reshape(2,4) # Do not confuse reshape with Transpose, reshape does it to what you specify not by flipping number of columns to rows and vice versa.

array([[12, 67, 35, 90],
       [12,  3,  8, 27]])

In [54]:
np.arange(0,11,2)  # This is telling np to make a range from 0 to 11 with a jump of 2.


array([ 0,  2,  4,  6,  8, 10])